title: Alex Piskun

logo: /assets/img/logo.jpeg
avatar: /assets/img/logo.jpeg

description: CV, projects and repositories

show_downloads: false

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: piskun.aleksey@gmail.com
  facebook:
  flickr:
  github: viktorsapozhok
  instagram:
  linkedin: aleksey-piskun-96121590
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

google_analytics:

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile